### PR TITLE
Replace setuptools_scm version with new get_version script (Infra)

### PR DESCRIPTION
**Pull request by Hook25**
## Description

We have decided to use an alternative way to calculate the version. We have landed the script to do so in 7b2e8d095dcb1419671cd2d6f5a13c83b4819f30. This PR replaces all occurrences of setuptools_scm with this new script with the appropriate calling parameters. 

## Resolved issues

Resolves: https://warthogs.atlassian.net/browse/CHECKBOX-1052

## Documentation

This changes the version of produced artifacts to the one generated by the new script documented [here (link)](https://github.com/canonical/checkbox/blob/2349a73ac8c8aa81b12fa5b92c0247edb3324c7d/tools/release/get_version.py#L20)

The way the artifacts are built isn't changed by this so that will not be documented further.

## Tests

N/A

### CODE REVIEW

**Comment by kissiel** [comment]
> ## Documentation
> Actual behavior is unchanged, the version should be the new one


```
❯ for series in series*; do diff $series/version.txt ../../main/checkbox-core-snap/$series/version.txt; done 
1c1
< v3.3.0-dev8
---
> 3.2.1.dev5+g2349a73ac
1c1
< v3.3.0-dev8
---
> 3.2.1.dev5+g2349a73ac
1c1
< v3.3.0-dev8
---
> 3.2.1.dev5+g2349a73ac
1c1
< v3.3.0-dev8
---
> 3.2.1.dev5+g2349a73ac
```

**Comment by Hook25** [comment]
The mismatch is due to the fact that setuptools_scm seems to be tracking only origin/main commits while get_version.py is tracking HEAD. Do we want to change this so that is uniform?

**Comment by kissiel** [comment]
what I wanted to know is why 5 + 4 = 8
5: git log v3.2.0..origin/main --oneline |wc
4: git log origin/main..HEAD --oneline |wc
8: git log v3.2.0..HEAD --oneline |wc

but that's because your branch is rebased on a main~1 :D

**Review by kissiel — APPROVED** [review]
Great stuff, +1

**Pull request merged**
