### PR TITLE
Fix put crash metabox

### PR DESCRIPTION
**Pull request by Hook25**
## Description

If a scenario contains a Put action to a location that can not be written, this will raise an uncaught pylxd.exceptions.NotFound crashing metabox

## Resolved issues

Fixes: https://github.com/canonical/checkbox/issues/472

## Documentation

N/A

## Tests

N/A

### CODE REVIEW

**Review by pieqq — APPROVED** [review]
Looks good to me!

Just FYI, `pylxd.files.put()` is super limited in what it can do. It's impossible, for instance, to recursively create the directories if they are missing. That's why I added those few lines to create the direct parent at the very least, but it's not ideal...

**Comment by kissiel** [comment]
I'm not so sure about this patch. It hides the fact that there's something very wrong about LXD, and not only about putting the file.
Only the errors related to putting the files should be handled by our, metabox `put` part. All other exceptions should bubble up.
What was the original cause of the problem?

**Comment by Hook25** [comment]
As you can see in this past run [of metabox (link)](https://github.com/canonical/checkbox/actions/runs/5011145012/jobs/8981674293#step:7:513) PyLXD does not seem to deterministically rise `NotFound` if it can't write to a location. Either way, the test runner should not crash if an exception is thrown by the `Put` api, it should just mark the test as failed.

**Comment by kissiel** [comment]
> As you can see in this past run [of metabox (link)](https://github.com/canonical/checkbox/actions/runs/5011145012/jobs/8981674293#step:7:513) PyLXD does not seem to deterministically rise `NotFound` if it can't write to a location. Either way, the test runner should not crash if an exception is thrown by the `Put` api, it should just mark the test as failed.

I disagree. The preparation of a scenario is not scenario's merit. The same would apply if you would be writing normal unit test in python and made a syntax error in the `setUp` method. Test harness would crash and not run any test. This _should_ crash, because the error you're catching here is scenario author's problem, not the thing's that metabox is asked to test.

**Comment by kissiel** [comment]
Or to be more precise can checkbox's bug cause this error?

**Comment by Hook25** [comment]
Short answer: no, but we can be more descriptive. The exception contains the "response" with the error message from lxd, we can log it in debug to make any eventual future problem easier to pin down. What do you think?

The function that ends up being called by the `Put` is [the instance function of the file manager](https://github.com/lxc/pylxd/blob/1f1f903d6512f0fb9ee030d051278c6c90f068b6/pylxd/models/instance.py#L113) that clearly states in its documentation that it is going to raise only `LXDAPIException` errors, and so it does at [line 121](https://github.com/lxc/pylxd/blob/1f1f903d6512f0fb9ee030d051278c6c90f068b6/pylxd/models/instance.py#L121). We get a specific exception instead of the generic one because one "deeper" function in [client.py](https://github.com/lxc/pylxd/blob/1f1f903d6512f0fb9ee030d051278c6c90f068b6/pylxd/client.py#L233) asserts the result it gets back is in [200, 202]. Doing so [this function](https://github.com/lxc/pylxd/blob/1f1f903d6512f0fb9ee030d051278c6c90f068b6/pylxd/client.py#L146) tries to create a specific exception for two cases, one of whom is ours. From the [API documentation](https://linuxcontainers.org/lxd/api/master/#/instances/instance_files_post) the possible error return codes are 4 of whom just 1 is handled by the function, the other 3 will raise a generic `LXDAPIException` leaving little chance for us to separate them into different "categories" (without manually parsing out of the response the `error_code`, but if we do that, when should we crash? 400? 403? 500? I don't know

**Comment by kissiel** [comment]
Yeah, I feel the same way about "parsing" the exception to find the details.
I really would like to somehow differentiate between a problem with the test and problem with what the test is testing... We shouldn't treat test-harness errors the same way as failed assertions of the test. 

ATM failure to put something in a container clearly signifies a problem with the test logic, which should be reported to the test author with all the goodies that come with a traceback.

**Comment by kissiel** [comment]
Some test harnesses have the third outcome for the test - "CRASHED". Maybe that's the way forward.

**Comment by pieqq** [comment]
Following a discussion we had earlier today, the best way to proceed would be:

- let the test harness crash. It's not normal that the test is trying to put a file where it cannot, so there is something fishy here.
- add debugging information to have something more meaninful than just `file not found` or `pylxdAPIException`.

**Review by pieqq — APPROVED** [review]
+1, thanks!

**Pull request merged**
