### PR TITLE
Update gadget interface validation test plan (BugFix)

### PR DESCRIPTION
**Pull request by stanley31huang**
update ce-oem-automated test plan and gadget interface test cases

## Description
There are two major changes in this PR
1. include the `ce-oem-gadget-automated` into the nested part of `ce-oem-automated`
2. remove the `also-after-suspend` flag from the gadget interface tests.

## Resolved issues
N/A

## Documentation
N/A

## Tests
Passed the provider validation locally.

### CODE REVIEW

**Review by LiaoU3 — COMMENTED** [review]
Why don't we want to run the after suspend tests?

**Comment by stanley31huang** [comment]
> Why don't we want to run the after suspend tests?

IIRC, the snap interfaces are initialized when the snap is installed, so we should be safe to ignore those tests in Post-suspend stage.

**Comment by LiaoU3** [comment]
> > Why don't we want to run the after suspend tests?
> 
> IIRC, the snap interfaces are initialized when the snap is installed, so we should be safe to ignore those tests in Post-suspend stage.

I don't get it. What will happen if we test them after suspend?

**Comment by stanley31huang** [comment]
> > > Why don't we want to run the after suspend tests?
> > 
> > 
> > IIRC, the snap interfaces are initialized when the snap is installed, so we should be safe to ignore those tests in Post-suspend stage.
> 
> I don't get it. What will happen if we test them after suspend?

I mean the snap interfaces are initialized when it is installed. Thus, the interface will not be affected during the suspend and resume process (unlike the kernel driver, which may experience changes or need reinitialization) . So we don't need to have the after-suspend tests.

**Review by LiaoU3 — APPROVED** [review]
+1

**Pull request merged**
