### PR TITLE
Automate DVD test (New)

### PR DESCRIPTION
**Pull request by eugene-yujinwu**
This PR was used to automated the DVD test, which used to be a manual test. After the change, the manual tests will be removed from the manual test plan, and a DVD read test will be added to the automatic test plan. 
If the DUT with a DVD or Bluray device, before run the automatic test, a new manifest item "has_dvd_bluray_inserted" will be asked. If the has_dvd_bluray_inserted had been labeled as yes, and a DVD or bluray disc was insterted. The DVD/Bluray read test will be run in the Automatic test.
     * Remove DVD test from the Manual test plan
     * Add a DVD read test to Automatic test plan
     * Add a manifest has_dvd_bluray_inserted
 
Please refter the https://warthogs.atlassian.net/browse/OEMQA-4085 for more info and the test results.

### CODE REVIEW

**Review by LiaoU3 — APPROVED** [review]
+1

**Comment by hanhsuan** [comment]
@eugene-yujinwu  Do you know where the `optical-cert-blockers` and `after-suspend-optical-cert-blockers` are used?

**Comment by eugene-yujinwu** [comment]
> @eugene-yujinwu Do you know where the `optical-cert-blockers` and `after-suspend-optical-cert-blockers` are used?

@hanhsuan sorry, I didn't get you. Have no idea about this.

**Comment by hanhsuan** [comment]
> > @eugene-yujinwu Do you know where the `optical-cert-blockers` and `after-suspend-optical-cert-blockers` are used?
> 
> @hanhsuan sorry, I didn't get you. Have no idea about this.

You modified these test plans, but I couldn't find where they are used.

**Comment by eugene-yujinwu** [comment]
> > > @eugene-yujinwu Do you know where the `optical-cert-blockers` and `after-suspend-optical-cert-blockers` are used?
> > 
> > 
> > @hanhsuan sorry, I didn't get you. Have no idea about this.
> 
> You modified these test plans, but I couldn't find where they are used.

Hi @hanhsuan , they are used in the providers/certification-client/units/client-cert-desktop-22-04.pxu, or providers/certification-client/units/client-cert-desktop-24-04.pxu, such as https://github.com/canonical/checkbox/blob/dae49f57fe73c8535c2ecb32b85b9d277e12edaa/providers/certification-client/units/client-cert-desktop-22-04.pxu#L118
And client-cert-odm-desktop-22-04.pxu, client-cert-odm-desktop-24-04.pxu

**Comment by hanhsuan** [comment]
> optical-cert-blockers

I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`

image

**Comment by eugene-yujinwu** [comment]
> > optical-cert-blockers
> 
> I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`
> 
> image

Ah, I got you. You mean these two test planes was not used by any other test plan. So we should just keep it unmodified, does it right?

**Comment by hanhsuan** [comment]
> > > optical-cert-blockers
> > 
> > 
> > I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`
> > image
> 
> Ah, I got you. You mean these two test planes was not used by any other test plan. So we should just keep it unmodified, does it right?

Yes, you are right.

**Comment by eugene-yujinwu** [comment]
> > > > optical-cert-blockers
> > > 
> > > 
> > > I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`
> > > image
> > 
> > 
> > Ah, I got you. You mean these two test planes was not used by any other test plan. So we should just keep it unmodified, does it right?
> 
> Yes, you are right.



> > > > optical-cert-blockers
> > > 
> > > 
> > > I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`
> > > image
> > 
> > 
> > Ah, I got you. You mean these two test planes was not used by any other test plan. So we should just keep it unmodified, does it right?
> 
> Yes, you are right.



> > > > optical-cert-blockers
> > > 
> > > 
> > > I mean `optical-cert-blockers` and `after-suspend-optical-cert-blockers`
> > > image
> > 
> > 
> > Ah, I got you. You mean these two test planes was not used by any other test plan. So we should just keep it unmodified, does it right?
> 
> Yes, you are right.

Thank you @hanhsuan , good catch. A new commit was pushed and the tests was added back.

**Review by pieqq — APPROVED** [review]
Good idea to fully automate this test!

I tested it on my laptop with and without an external CD drive connected.

When the CD drive is connected, the test appears and I can confirm in the Manifest screen whether or not a DVD/BluRay has been inserted.

+1!

**Comment by eugene-yujinwu** [comment]
Thank you @pieqq , glad you are back:)

**Pull request merged**
