### PR TITLE
Don't use '-A' in network.py on non-numa systems (BugFix)

### PR DESCRIPTION
**Pull request by rodwsmith**
## Description
This PR fixes bug #570, which can cause the CPU load to spike if the CPU affinity is set incorrectly on systems that don't support NUMA features.

The fix involves identifying systems that lack NUMA support and _not_ passing the -A {nodes} option to iperf3 on such systems.

## Resolved issues

Resolves bug #570

Jira card: https://warthogs.atlassian.net/browse/SERVCERT-1183

## Documentation

No documentation changes required.

## Tests

Tested on lloobee (my own ARM64-based development system), which exhibited the bug. The new version drops the CPU load from 90%+ to about 35-40%, and increases the throughput by about 5% (from 88% to 93%, give or take a percent or two).

I've also tested on two servers in the Server Certification pool, torchtusk and whomp, to be sure the script doesn't create problems on systems that DO support NUMA. No unexpected problems arose. The change should result in exactly the same iperf3 command being used on such systems as the previous version of the script. Such systems were unaffected by the bug to begin with.

### CODE REVIEW

**Review by bladernr — DISMISSED** [review]
Looks good to me... thanks

**Review by Hook25 — CHANGES_REQUESTED** [review]
I have to ask a few changes here:
- codecov is complaining because we need a new test here, `sumarize_cpu` is untested
- it is kind of weird to return `-1` instead to throwing an exception. Would you consider changing this to raise an exception both if the file is not found or if it is found and contains a `-1`? That way anyone calling the function will not have to check if `-1` is a valid numa number or what is going on, if something is returned, it is valid, else an exception is thrown
- Minor: Change the title of the PR after rebasing on main, this is a bugfix so add a (bugfix) postfix to the title!

Ty

**Comment by kissiel** [comment]
I added tests and fixed the PR title.
The -1 as the node index is in line with what sysfs would report on a non-numa systems, so I left it in.

@hook please take another look

**Review by Hook25 — APPROVED** [review]
+1, if this causes a problem we can change in the future I guess

**Pull request merged**
