### PR TITLE
Fix udevadm.py to parser VRAID partition correctly (Bugfix)

### PR DESCRIPTION
**Pull request by seankingyang**
## Description
The DUT with VRAID, the udevadm.py could not parser the right thing.
Push this PR could fix this bug.

## Resolved issues

#482 udev_resource.py -f PARTITION failed with error

### CODE REVIEW

**Comment by stanley31huang** [comment]
I have verified this fixed on an IoT platform, which has Intel RST RAID enabled. And we could get the disk info by udev_resource.py scripts without errors.
```
path: /devices/virtual/block/md0
name: md0
bus: block
category: DISK

path: /devices/virtual/block/md126
name: md126
bus: block
category: DISK
product: Volume1_0
vendor: raid0
product_slug: Volume1_0
vendor_slug: raid0

path: /devices/virtual/block/md126/md126p1
name: md126p1
bus: block
product: Volume1_0
vendor: raid0
product_slug: Volume1_0
vendor_slug: raid0

path: /devices/virtual/block/md126/md126p2
name: md126p2
bus: block
product: Volume1_0
vendor: raid0
product_slug: Volume1_0
vendor_slug: raid0

path: /devices/virtual/block/md127
name: md127
bus: block
category: DISK
vendor: container
vendor_slug: container
```

But I found some disk tests might be failed with this change
```
# disk/stats_{name} test
ubuntu@ubuntu:~/checkbox-support$ sudo checkbox-iiotg-classic.shell 
checkbox-iiotg-classic runtime shell, type 'exit' to quit the session
root@ubuntu:/home/ubuntu/checkbox-support# python3 /snap/checkbox22/current/providers/checkbox-provider-base/bin/disk_stats_test.sh md126
  File "/snap/checkbox22/current/providers/checkbox-provider-base/bin/disk_stats_test.sh", line 23
    }
    ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' on line 15

# disk/read_performance_{name} test
root@ubuntu:/home/ubuntu/checkbox-support# python3 /snap/checkbox22/current/providers/checkbox-provider-base/bin/disk_read_performance_test.sh md126
  File "/snap/checkbox22/current/providers/checkbox-provider-base/bin/disk_read_performance_test.sh", line 51
    "usb" ) 
          ^
SyntaxError: unmatched ')'

# disk/storage_device_{name} test
root@ubuntu:/home/ubuntu/checkbox-support# python3 /snap/checkbox22/current/providers/checkbox-provider-base/bin/storage_test.py md126
Testing disk md126
identified as a disk...
test will be run on partition /dev/md126p2
/dev/md126p2 already mounted at /
456254.55078125MB of free space avaialble
Forcing memory setting to 8000MB
+ bonnie++ -d / -u root -r 8000
Using uid:0, gid:0.
Writing a byte at a time...done
Writing intelligently...done
Rewriting...done
Reading a byte at a time...done
Reading intelligently...done
start 'em...done...done...done...done...done...
Create files in sequential order...done.
Stat files in sequential order...done.
Delete files in sequential order...done.
Create files in random order...done.
Stat files in random order...done.
Delete files in random order...done.
Version  2.00       ------Sequential Output------ --Sequential Input- --Random-
                    -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
Name:Size etc        /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
ubuntu          16G 1318k  99  416m  33  407m  26 4443k  96  7.2g  99 +++++ +++
Latency              6199us   81539us   43831us    1868us      25us      53us
Version  2.00       ------Sequential Create------ --------Random Create--------
ubuntu              -Create-- --Read--- -Delete-- -Create-- --Read--- -Delete--
              files  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
                 16 +++++ +++ +++++ +++ +++++ +++ +++++ +++ +++++ +++ +++++ +++
Latency               545us     224us    2632us      39us      20us    2542us
1.98,2.00,ubuntu,1,1710984956,16G,,8192,5,1318,99,425571,33,417002,26,4443,96,7589910,99,+++++,+++,16,,,,,+++++,+++,+++++,+++,+++++,+++,+++++,+++,+++++,+++,+++++,+++,6199us,81539us,43831us,1868us,25us,53us,545us,224us,2632us,39us,20us,2542us

root@ubuntu:/home/ubuntu/checkbox-support# python3 /snap/checkbox22/current/providers/checkbox-provider-base/bin/storage_test.py md127
Testing disk md127
identified as a disk...
ERROR: No suitable partitions found on device /dev/md127
```

**Review by kissiel — CHANGES_REQUESTED** [review]
could `checkbox-support/checkbox_support/parsers/tests/udevadm_data/With_VRAID.txt` be reduced to contain only the parts that are *interesting*?
16kLOC takes quite a while to parse, it's also a burden for the repo. I know we've committed files like that in the past, but we definitely need to stop.

**Comment by seankingyang** [comment]
Minimize the input data(`With_VRAID.txt`), and modify the `test_udevadm.py` to remove the unnecessary code which added former commit.

**Review by kissiel — APPROVED** [review]
Thank you so much for making the test run in a reasonable time!
+1

**Pull request merged**
