### PR TITLE
Remove require for rt-tests (BugFix)

### PR DESCRIPTION
**Pull request by LiaoU3**
## Description
Since we have package `rt-tests` in [snapcraft](https://github.com/canonical/checkbox/blob/90acaebc6997387906e7ae832fef0dbe22b17809/checkbox-core-snap/series24/snap/snapcraft.yaml#L303) and [packaging](https://github.com/canonical/checkbox/blob/90acaebc6997387906e7ae832fef0dbe22b17809/providers/base/units/rt-performance-tests/packaging.pxu#L5), there is no need to require the package in the tests.

## Resolved issues
N/A

## Documentation
N/A

## Tests
N/A

### CODE REVIEW

**Comment by pieqq** [comment]
Why is this removal needed? Having `package.name` can ensure the test runs only when that package is available (for instance, when running using a virtual environment).

**Comment by LiaoU3** [comment]
@pieqq It is not working on the snap version of checkbox, since we package `rt-tests` into the stage-packages, it is not going to be shown in the resource job `package`, due to the fact that `package` only list the debian package installed on the local

**Review by zongminl — CHANGES_REQUESTED** [review]
Please use snap resource job instead if this is a snap package to be checked

**Comment by pieqq** [comment]
> Please use snap resource job instead if this is a snap package to be checked

That, or the `executable` resource.

**Comment by LiaoU3** [comment]
`executable` makes more sense

**Review by zongminl — APPROVED** [review]
LGTM

**Review by pieqq — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
