### PR TITLE
Update vendor RPyC 5.3.1

### PR DESCRIPTION
**Pull request by Hook25**
## Description

This updates RPyC vendor module to version `5.3.1`.

## Resolved issues

N/A

## Documentation

- The version was copied from upstream 5.3.1
- All imports were fixed to the vendor ones 
- f-strings were converted to `.format` to maintain py3.5 compatibility

## Tests

- [ ] Launch one checkbox-cli service instance
- [ ] Connect to it via a checkbox-cli remote instance
- [ ] Run a test 

Note: I am unable to prove an incompatibility between the new version of the library and the old one both client5/server4 and server4/client5 although I presumed that to be the case. Both experiments run to completion without crashing or any change to the output, maybe there is a better way to test this.

### CODE REVIEW

**Comment by Hook25** [comment]
I have tested this with the following metabox configuration:
```python
configuration = {
    'remote': {
        'origin': 'source',
        'releases': ['jammy', 'focal', 'bionic'],
    },
    'service': {
        'origin': 'source',
        'releases': ['jammy', 'focal', 'bionic'],
    },
}
```

and launching it via the following command:
```bash
$ metabox --do-not-dispose --log DEBUG test.py
```

It cleared all tests
```bash
15:03:19 | SUCCESS  Ran 72 scenarios in 2446.682s
```

I think we can un-draft this and merge it

**Comment by pieqq** [comment]
We tested the following scenarios:

Test Device 1 (TD1): laptop running Checkbox snap v2.5 from stable channel (RPyC 4.x)
Test Device 2 (TD2): laptop running the code from this branch in a python virtual env (RPyC 5.3.1)

# Test 1

TD1 connects to TD2 through remote:

```
checkbox-cli remote <TD2_IP>
```

Select Smoke test plan and run it.

The run completes and the HTML report contains all expected information -> OK

# Test 2

TD2 connects to TD1 through remote:

```
checkbox-cli remote <TD1_IP>
```

Select Smoke test plan and run it.

The run completes and the HTML report contains all expected information -> OK

**Review by pieqq — APPROVED** [review]
+1. Thanks!

**Comment by kissiel** [comment]
Incredibly, indeed the combinations of different versions work perfectly. Awesome stuff. +1

**Pull request merged**
