### PR TITLE
Add cert-blocker status based on coverage guide for IoT test plans (BugFix)

### PR DESCRIPTION
**Pull request by pieqq**
## Description

The "[Internet of Things Certified Hardware Coverage for Ubuntu Core 22 / Ubuntu 22.04](https://canonical-certification-docs.readthedocs-hosted.com/preview/iot/Coverage_Guide_IoT-22.04/)" document specifies what jobs should be considered as blockers.

For IoT devices, the after-suspend jobs are not considered blockers, so they have been left out.

### Considerations

The document I used as a "source of truth" specifies a few things that look suspicious. Feedback from other teams would be appreciated:

- Are we supposed to [support USB-C DP connection on IoT devices?](https://canonical-certification-docs.readthedocs-hosted.com/preview/iot/Coverage_Guide_IoT-22.04/#usb-type-c-usb-3-1)
- Same question as above for [Thunderbolt on IoT devices](https://canonical-certification-docs.readthedocs-hosted.com/preview/iot/Coverage_Guide_IoT-22.04/#thunderbolt)

## Resolved issues

CER-2593

## Tests

Running a `list-bootstrapped` of the `client-cert-iot-ubuntucore-22` test plan on my laptop yields the following output:

*Notes:*

- I'm using checkbox from #1204 to have a default certification_status of `non-blocker`
- My laptop does not have WWAN, Serial, I2C, etc, so these tests get skipped when using `list-bootstrapped`, that's why they don't appear below

```
checkbox-cli list-bootstrapped -f "{id} [{certification_status}]\n" "com.canonical.certification::client-cert-iot-ubuntucore-22"
(...)
manifest [non-blocker]
executable [non-blocker]
interface [non-blocker]
connections [non-blocker]
model_assertion [non-blocker]
serial_assertion [non-blocker]
net_if_management [non-blocker]
net_if_management_attachment [non-blocker]
lspci_attachment [non-blocker]
lsusb_attachment [non-blocker]
rtc [non-blocker]
sleep [non-blocker]
parts_meta_info_attachment [non-blocker]
miscellanea/device_check [non-blocker]
requirements [non-blocker]
cpuinfo [non-blocker]
dpkg [non-blocker]
sysfs_attachment [non-blocker]
lspci_standard_config_json [non-blocker]
efi [non-blocker]
lsblk_attachment [non-blocker]
snap [non-blocker]
device [non-blocker]
dmi_present [non-blocker]
raw_devices_dmi_json [non-blocker]
udev_attachment [non-blocker]
lsb [non-blocker]
uname [non-blocker]
modprobe_json [non-blocker]
meminfo [non-blocker]
environment [non-blocker]
udev_json [non-blocker]
dmi [non-blocker]
kernel_cmdline_attachment [non-blocker]
dmi_attachment [non-blocker]
package [non-blocker]
module [non-blocker]
system_info_json [non-blocker]
cdimage [non-blocker]
dkms_info_json [non-blocker]
miscellanea/submission-resources [non-blocker]
info/systemd-analyze [non-blocker]
info/systemd-analyze-critical-chain [non-blocker]
ubuntucore/os-reinstall-mode [non-blocker]
ubuntucore/os-recovery-mode [non-blocker]
ubuntucore/sshd [non-blocker]
audio/detect-playback-devices [non-blocker]
audio/alsa-playback [blocker]
bluetooth/keyboard-manual [blocker]
ethernet/wol_S5_enp0s31f6 [non-blocker]
ethernet/wol_S4_enp0s31f6 [non-blocker]
ethernet/wol_S3_enp0s31f6 [non-blocker]
ethernet/hotplug-enp0s31f6 [non-blocker]
led/power [blocker]
led/power-blink-suspend [non-blocker]
led/bluetooth [non-blocker]
led/serial [blocker]
led/fn [non-blocker]
mediacard/cf-insert [non-blocker]
mediacard/cf-storage [non-blocker]
mediacard/cf-remove [non-blocker]
mediacard/mmc-insert [non-blocker]
mediacard/mmc-storage [non-blocker]
mediacard/mmc-remove [non-blocker]
mediacard/ms-insert [non-blocker]
mediacard/ms-storage [non-blocker]
mediacard/ms-remove [non-blocker]
mediacard/msp-insert [non-blocker]
mediacard/msp-storage [non-blocker]
mediacard/msp-remove [non-blocker]
mediacard/sd-insert [non-blocker]
mediacard/sd-storage [non-blocker]
mediacard/sd-remove [non-blocker]
mediacard/sdhc-insert [non-blocker]
mediacard/sdhc-storage [non-blocker]
mediacard/sdhc-remove [non-blocker]
mediacard/sdxc-insert [non-blocker]
mediacard/sdxc-storage [non-blocker]
mediacard/sdxc-remove [non-blocker]
mediacard/xd-insert [non-blocker]
mediacard/xd-storage [non-blocker]
mediacard/xd-remove [non-blocker]
monitor/dvi [blocker]
monitor/hdmi [blocker]
monitor/dvi-to-vga [non-blocker]
monitor/hdmi-to-vga [non-blocker]
monitor/displayport_hotplug [blocker]
monitor/vga [non-blocker]
rtc/battery [blocker]
serial/rs232-console [blocker]
snappy/os-refresh [non-blocker]
snappy/os-revert [non-blocker]
usb/hid [blocker]
usb/insert [blocker]
usb/storage-automated [blocker]
usb/remove [blocker]
usb-c/c-to-a-adapter/hid [non-blocker]
usb [non-blocker]
usb-c/c-to-a-adapter/insert [non-blocker]
usb-c/c-to-a-adapter/storage-automated [non-blocker]
usb-c/c-to-a-adapter/remove [non-blocker]
usb-c/hid [non-blocker]
usb-c/insert [non-blocker]
usb-c/storage-automated [non-blocker]
usb-c/remove [non-blocker]
usb-c-otg/g_serial [non-blocker]
usb-c-otg/g_serial-cleanup [non-blocker]
usb-c-otg/g_mass_storage [non-blocker]
usb-c-otg/g_mass_storage-cleanup [non-blocker]
usb-c-otg/g_ether [non-blocker]
usb-c-otg/g_ether-cleanup [non-blocker]
usb3/insert [non-blocker]
usb3/storage-automated [non-blocker]
usb3/remove [non-blocker]
thunderbolt3/insert [blocker]
thunderbolt3/storage-test [blocker]
thunderbolt3/remove [blocker]
wifi_interface_mode [non-blocker]
wireless/wifi_ap_open_b_no_sta_wlp0s20f3_manual [non-blocker]
wireless/wifi_ap_open_g_no_sta_wlp0s20f3_manual [non-blocker]
wireless/wifi_ap_wpa_b_no_sta_wlp0s20f3_manual [non-blocker]
wireless/wifi_ap_wpa_g_no_sta_wlp0s20f3_manual [non-blocker]
wwan/detect-manual [non-blocker]
wwan/check-sim-present-manual [non-blocker]
wwan/scan-networks-manual [non-blocker]
wwan/gsm-connection-interrupted-manual [non-blocker]
cpu/clocktest [non-blocker]
disk/stats_dm-1 [non-blocker]
wireless_sta_protocol [non-blocker]
wireless/wireless_connection_wpa_ac_nm_wlp0s20f3 [blocker]
wireless/wireless_connection_wpa_ax_nm_wlp0s20f3 [blocker]
wireless/wireless_connection_wpa3_ax_nm_wlp0s20f3 [blocker]
ethernet/ping_enp0s31f6 [blocker]
wireless/wireless_connection_wpa_bg_nm_wlp0s20f3 [blocker]
wireless/wireless_connection_wpa_n_nm_wlp0s20f3 [blocker]
wireless/wireless_connection_wpa_ax_np_wlp0s20f3 [blocker]
location/status [non-blocker]
cpu/topology [blocker]
wireless/wifi_ap_wpa_g_no_sta_wlp0s20f3_auto [non-blocker]
wireless/wifi_ap_open_b_no_sta_wlp0s20f3_auto [non-blocker]
wireless/wifi_ap_wpa_g_with_sta_wlp0s20f3_auto [non-blocker]
wireless/wireless_connection_open_ac_np_wlp0s20f3 [blocker]
wireless/wifi_ap_wpa_b_with_sta_wlp0s20f3_auto [non-blocker]
wireless/wireless_connection_open_ax_np_wlp0s20f3 [blocker]
wireless/wireless_connection_open_bg_nm_wlp0s20f3 [blocker]
audio/detect-capture-devices [non-blocker]
wireless/wireless_scanning_wlp0s20f3 [non-blocker]
disk/read_performance_dm-1 [non-blocker]
wireless/wireless_connection_wpa_ac_np_wlp0s20f3 [blocker]
wwan/detect [blocker]
wireless/wireless_connection_open_n_nm_wlp0s20f3 [blocker]
socketcan/modprobe_vcan [non-blocker]
socketcan/send_packet_local_eff_virtual [non-blocker]
wireless/wifi_ap_setup_wizard_wlp0s20f3_auto [non-blocker]
wireless/wireless_connection_wpa_n_np_wlp0s20f3 [blocker]
wireless/wifi_ap_open_g_no_sta_wlp0s20f3_auto [non-blocker]
wireless/check_iwlwifi_microcode_crash_wlp0s20f3 [non-blocker]
wireless/wireless_connection_open_ax_nm_wlp0s20f3 [blocker]
wireless/nmcli_wifi_ap_bg_wlp0s20f3 [non-blocker]
socketcan/send_packet_local_sff_virtual [non-blocker]
wireless/wireless_connection_open_bg_np_wlp0s20f3 [blocker]
bluetooth/detect-output [non-blocker]
bluetooth/bluetooth_obex_send [non-blocker]
disk/storage_device_dm-1 [non-blocker]
wireless/wireless_connection_open_n_np_wlp0s20f3 [blocker]
audio/alsa-loopback-automated [blocker]
socketcan/send_packet_local_fd_virtual [non-blocker]
wireless/wireless_connection_wpa3_ax_np_wlp0s20f3 [blocker]
ethernet/detect [blocker]
disk/detect [non-blocker]
wireless/wireless_connection_wpa_bg_np_wlp0s20f3 [blocker]
ipv6_detect [non-blocker]
ipv6_link_local_address_enp0s31f6 [non-blocker]
cpu_offlining [non-blocker]
cpu/offlining_test [non-blocker]
camera/detect [non-blocker]
camera/multiple-resolution-images_video0 [non-blocker]
wireless/detect [blocker]
usb/storage-detect [non-blocker]
wireless/nmcli_wifi_ap_a_wlp0s20f3 [non-blocker]
wireless/wifi_ap_wpa_b_no_sta_wlp0s20f3_auto [non-blocker]
wireless/wireless_connection_open_ac_nm_wlp0s20f3 [blocker]
suspend/suspend_advanced_auto [non-blocker]
after-suspend-audio/alsa-playback [blocker]
after-suspend-bluetooth/keyboard-manual [non-blocker]
after-suspend-ethernet/detect [blocker]
after-suspend-ethernet/hotplug-enp0s31f6 [blocker]
after-suspend-monitor/dvi [non-blocker]
after-suspend-monitor/hdmi [non-blocker]
after-suspend-monitor/dvi-to-vga [non-blocker]
after-suspend-monitor/hdmi-to-vga [non-blocker]
after-suspend-monitor/displayport_hotplug [non-blocker]
after-suspend-monitor/vga [non-blocker]
networking/info_device1_enp0s31f6 [non-blocker]
after-suspend-networking/info_device1_enp0s31f6 [blocker]
after-suspend-serial/rs232-console [non-blocker]
after-suspend-usb/hid [non-blocker]
after-suspend-usb/insert [non-blocker]
after-suspend-usb/storage-automated [non-blocker]
after-suspend-usb/remove [non-blocker]
after-suspend-usb-c/c-to-a-adapter/hid [non-blocker]
after-suspend-usb-c/c-to-a-adapter/insert [non-blocker]
after-suspend-usb-c/c-to-a-adapter/storage-automated [non-blocker]
after-suspend-usb-c/c-to-a-adapter/remove [non-blocker]
after-suspend-usb-c/hid [non-blocker]
after-suspend-usb-c/insert [non-blocker]
after-suspend-usb-c/storage-automated [non-blocker]
after-suspend-usb-c/remove [non-blocker]
after-suspend-usb-c-otg/g_serial [non-blocker]
after-suspend-usb-c-otg/g_serial-cleanup [non-blocker]
after-suspend-usb-c-otg/g_mass_storage [non-blocker]
after-suspend-usb-c-otg/g_mass_storage-cleanup [non-blocker]
after-suspend-usb-c-otg/g_ether [non-blocker]
after-suspend-usb-c-otg/g_ether-cleanup [non-blocker]
after-suspend-usb3/insert [non-blocker]
after-suspend-usb3/storage-automated [non-blocker]
after-suspend-usb3/remove [non-blocker]
after-suspend-thunderbolt3/insert [blocker]
after-suspend-thunderbolt3/storage-test [blocker]
after-suspend-thunderbolt3/remove [blocker]
after-suspend-wireless/wifi_ap_open_b_no_sta_wlp0s20f3_manual [non-blocker]
after-suspend-wireless/wifi_ap_open_g_no_sta_wlp0s20f3_manual [non-blocker]
after-suspend-wireless/wifi_ap_wpa_b_no_sta_wlp0s20f3_manual [non-blocker]
after-suspend-wireless/wifi_ap_wpa_g_no_sta_wlp0s20f3_manual [non-blocker]
after-suspend-wwan/detect-manual [non-blocker]
after-suspend-wwan/scan-networks-manual [non-blocker]
after-suspend-wwan/check-sim-present-manual [non-blocker]
after-suspend-wwan/gsm-connection-interrupted-manual [non-blocker]
firmware/fwts_desktop_diagnosis [non-blocker]
firmware/fwts_desktop_diagnosis_results.log.gz [non-blocker]
acpi/oem_osi [non-blocker]
bluetooth/detect [non-blocker]
bluetooth/bluez-controller-detect [non-blocker]
camera/roundtrip-qrcode_video0 [non-blocker]
cpu/scaling_test [blocker]
cpu/scaling_test-log-attach [non-blocker]
cpu/maxfreq_test [blocker]
cpu/maxfreq_test-log-attach [non-blocker]
cpu/cstates [blocker]
cpu/cstates_results.log [non-blocker]
disk/check-software-raid [non-blocker]
docker/info [non-blocker]
docker/version [non-blocker]
docker/run_ [non-blocker]
docker/interative_ [non-blocker]
docker/diff_ [non-blocker]
docker/copy_ [non-blocker]
docker/inspect_ [non-blocker]
docker/kill_ [non-blocker]
docker/build-single_ [non-blocker]
docker/start-stop_ [non-blocker]
docker/deploy-registry_ [non-blocker]
docker/export-and-import_ [non-blocker]
docker/save-and-load_ [non-blocker]
docker/commit_ [non-blocker]
docker/update_ [non-blocker]
docker/restart-on-failure_ [non-blocker]
docker/restart-always_ [non-blocker]
docker/compose-single_ [non-blocker]
docker/compose-and-basic_ [non-blocker]
docker/compose-restart_ [non-blocker]
i2c/i2c-bus-detect [blocker]
i2c/i2c-device-detect [blocker]
ubuntu_core_features [non-blocker]
kernel-snap/booted-kernel-matches-current-grub [non-blocker]
memory/info [blocker]
networking/predictable_names [non-blocker]
power-management/warm-reboot [blocker]
power-management/post-warm-reboot [blocker]
power-management/cold-reboot [blocker]
power-management/post-cold-reboot [blocker]
snappy/snap-list [non-blocker]
snappy/snap-search [non-blocker]
snappy/snap-install [non-blocker]
snappy/snap-refresh-automated [non-blocker]
snappy/snap-revert-automated [non-blocker]
snappy/snap-reupdate-automated [non-blocker]
snappy/snap-remove [non-blocker]
snappy/test-store-install-beta [non-blocker]
snappy/test-store-install-edge [non-blocker]
snappy/test-system-confinement [non-blocker]
snappy/test-snaps-confinement [non-blocker]
snap_revision_info [non-blocker]
snapd/snap-refresh-snapd-snapd-to-base-rev [non-blocker]
snapd/log-attach-after-snap-refresh-snapd-snapd-to-base-rev [non-blocker]
snapd/snap-verify-after-refresh-snapd-snapd-to-base-rev [non-blocker]
snapd/snap-revert-snapd-snapd-from-base-rev [non-blocker]
snapd/log-attach-after-snap-revert-snapd-snapd-from-base-rev [non-blocker]
snapd/snap-verify-after-revert-snapd-snapd-from-base-rev [non-blocker]
snapd/snap-refresh-snapd-snapd-to-stable-rev [non-blocker]
snapd/log-attach-after-snap-refresh-snapd-snapd-to-stable-rev [non-blocker]
tpm2/fwts-event-log-dump [non-blocker]
clevis-encrypt-tpm2/precheck [blocker]
clevis-encrypt-tpm2/detect-rsa-capabilities [blocker]
clevis-encrypt-tpm2/rsa [blocker]
clevis-encrypt-tpm2/detect-ecc-capabilities [blocker]
clevis-encrypt-tpm2/ecc [blocker]
watchdog/detect [non-blocker]
watchdog/systemd-config [non-blocker]
watchdog/trigger-system-reset-auto [non-blocker]
watchdog/post-trigger-system-reset-auto [non-blocker]
after-suspend-audio/detect-playback-devices [non-blocker]
after-suspend-audio/detect-capture-devices [non-blocker]
after-suspend-audio/alsa-loopback-automated [non-blocker]
after-suspend-bluetooth/bluetooth_obex_send [non-blocker]
after-suspend-ethernet/ping_enp0s31f6 [blocker]
after-suspend-location/status [non-blocker]
after-suspend-usb/storage-detect [non-blocker]
after-suspend-wireless/wireless_scanning_wlp0s20f3 [non-blocker]
after-suspend-wireless/wireless_connection_open_ax_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_ac_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_bg_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_n_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_ax_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa3_ax_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_ac_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_bg_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_n_nm_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_ax_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_ac_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_bg_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_open_n_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_ax_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa3_ax_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_ac_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_bg_np_wlp0s20f3 [blocker]
after-suspend-wireless/wireless_connection_wpa_n_np_wlp0s20f3 [blocker]
after-suspend-wireless/check_iwlwifi_microcode_crash_wlp0s20f3 [non-blocker]
after-suspend-wwan/detect [non-blocker]
```

## WARNING: This modifies com.canonical.certification::sru-server

### CODE REVIEW

**Comment by pieqq** [comment]
I've checked the cert-blocker status on the Desktop 22.04 test plan and it looks appropriate, so no changes are required. This PR is ready for review.

**Review by zongminl — DISMISSED** [review]
Hi @pieqq,
A few years earlier, there was a discussion between Cert/CE/OEMQA and the decision made in that meeting was[1] 
> Any job included in the project provider is a blocker

And the "CE IoT QA - Enablement Cycle QA Process" document has been updated according to that conclusion[2]

If we're now only adding blocker certification status according to the jammy test coverage guide then the certification scope will be changed for commercial enablement projects and ODM program projects as well.
Therefore I'd like to suggest applying blocker certification status to all the test jobs included in the client-cert-iot and client-cert-odm test plans.

[1] https://docs.google.com/document/d/1j0sOvJSODp_qlsTvjQcJA6umHSv-B18h8e506fz1sSE/edit#heading=h.6llmkwta1g0g
[2] https://docs.google.com/document/d/1QIaNbzu0bQXLMNTKPHJ21Tvb0upgHKb3UVvn0KQV6h8/edit#heading=h.pvqm21uto89l

**Comment by pieqq** [comment]
> Therefore I'd like to suggest applying blocker certification status to all the test jobs included in the client-cert-iot and client-cert-odm test plans.

The `client-cert-odm` test plans include desktop test plans (e.g. `client-cert-odm-desktop-24-04-manual`), server test plans (e.g. `client-cert-odm-server-18-04-manual`) and "Ubuntu Core" test plans (e.g. `client-cert-odm-ubuntucore-24-automated`). Do we want to make every jobs in all of these test plans as blockers? This goes beyond the links you provided, @zongminl, because the documents you provided are about IoT projects.

Should I only add the certification status overrides to the `cert-odm-ubuntucore-*` test plans?

**Comment by zongminl** [comment]
I'd say we should at least add the certification status to:
`
client-cert-iot-server-.*
client-cert-iot-ubuntucore-.*
client-cert-iot-desktop-.*
`

As for the certification criteria for ODM program I agree with you, this should go to someone more familiar with certifying ODM program devices.

**Review by zongminl — APPROVED** [review]
LGTM, thank you

**Pull request merged**
