### PR TITLE
Documentation migration

### PR DESCRIPTION
**Pull request by pieqq**
## Description

The goal of this PR is to migrate our existing pages to the new `docs` directory, and do some cleanup. Namely:

- Update the welcome page with a description of the application
- Copy *.rst files from checkbnox-ng/docs to docs/ following the proposed [structure](https://docs.google.com/spreadsheets/d/1RiCawU15NYpcC85_w444ZSHOAVHWE40XQEy8koz8aUU/edit#gid=0)
- Remove the starter pack boilerplate

I migrated everything except `snappy.rst` as I thought it was not relevant anymore (checkbox-snappy is not in use, and the content of that page is basically a mega-tutorial with information present elsewhere).

## Resolved issues

CHECKBOX-610

## Tests

Tested locally using `make run` (super useful stuff!)

I checked if images and links worked as before, and it seems OK.

To test locally:

1. Checkout this branch
2. Go to the `docs/` directory, and run `make install`
3. Run `make run` -> you should be able to access the built documentation locally.

### CODE REVIEW

**Comment by pieqq** [comment]
The "Spelling check" steps of our workflow fails because of a lot of technical terms in our pages. Will have to look into that later.

**Comment by yphus** [comment]
Good work, just one comment. I'd not create a section for "Project and community" (on the left side bar) but rather add both bugs.rst and contributing.rst as links under the footer section of the main page, right here:

```
Project and community

Checkbox is a member of the Ubuntu family. It’s an open source project that warmly welcomes community projects, contributions, suggestions, fixes and constructive feedback.

    This project follows the Ubuntu Code of Conduct
    Get support
    Join our online chat
    Contribute                                  <-- here
    Reporting bugs                          <-- and here
    Thinking about using Checkbox for your next project? Get in touch!
```

**Comment by pieqq** [comment]
> Please add :orphan: to the top of the following files:
> 
>     * checkbox/docs/community/bugs.rst
> 
>     * checkbox/docs/community/contributing.rst
> 
> 
> To avoid a warning at build time: `WARNING: document isn't included in any toctree`

Done!

**Review by yphus — APPROVED** [review]
LGTM

**Pull request merged**
