### PR TITLE
fprintd should enroll a user, not a uid (BugFix)

### PR DESCRIPTION
**Pull request by binli**
$ sudo env | grep SUDO
SUDO_COMMAND=/usr/bin/env
SUDO_USER=ubuntu
SUDO_UID=1001
SUDO_GID=1001

when running checkbox with sudo, it will 'fprintd-enroll 1001' and the test case will lock screen to let 'ubuntu' user to login, but at that time, it will not work because the user is not 'ubuntu'.

### CODE REVIEW

**Comment by pieqq** [comment]
/canonical/self-hosted-runners/run-workflows b5a58efd1583ef08ab443d68a4234a8b27e60b38

**Comment by binli** [comment]
/canonical/self-hosted-runners/run-workflows 56fadbfed3b2e9854ead93b3eca6dcaf6bdd3265

**Comment by binli** [comment]
@pieqq hi, the title sounds good in my side, do you know why the failure of 'PR Validation'? Thanks!

$ echo  "fprintd should enroll a user, not a uid (BugFix)" | grep -iP "\((infra|bugfix|new|breaking)\)$"
fprintd should enroll a user, not a uid (BugFix)

**Comment by pieqq** [comment]
/canonical/self-hosted-runners/run-workflows bf2d4f3af4417a752e7e3b583884f07734e4ea9f

**Comment by pieqq** [comment]
It's because we use self-hosted runners and they require some manual steps from people in the Cert team when someone submits their first PR... It should be fixed now.

I tried your PR with a laptop, but I couldn't get the fingerprint tests to work. I'll check again with another laptop tomorrow.

Quick question, what do you mean when you say "when running checkbox with sudo"? Do you run `sudo checkbox-cli`? Or do you run the job, and the job is using `user: root` so you know Checkbox runs this as sudo?

**Comment by binli** [comment]
@pieqq Oh, got it, thanks! And we met this issue when QA do finger printer test by manual, I need confirm with @eugene-yujinwu .
@eugene-yujinwu Do you run sudo checkbox-cli?

**Comment by eugene-yujinwu** [comment]
@binli @pieqq , actually this test case always run by root, 
"id: fingerprint/detect
flags: also-after-suspend
user: root
command: fprintd-list "${SUDO_UID:-$NORMAL_USER}"
so it will always use SUDO_UID other than NORMAL_USER.

**Comment by binli** [comment]
The original test result.

$ checkbox-cli run com.canonical.certification::fingerprint-full

------------[ Check if at least one fingerprint reader is detected ]------------                                                        
ID: com.canonical.certification::fingerprint/detect                                                                                     
Category: com.canonical.plainbox::fingerprint                       
... 8< -------------------------------------------------------------------------
Enter sudo password:                                                                                                                    
                                  
found 1 devices
Device at /net/reactivated/Fprint/Device/0
Using device /net/reactivated/Fprint/Device/0                       
User 1000 has no fingers enrolled for Synaptics Sensors.            
------------------------------------------------------------------------- >8 ---
Outcome: job passed      
Finalizing session that hasn't been submitted anywhere: checkbox-run-2023-11-07T11.47.29

With this commit, the result is here.

Outcome: job passed
==============[ Running job 2 / 2. Estimated time left: 0:00:01 ]===============
------------[ Check if at least one fingerprint reader is detected ]------------
ID: com.canonical.certification::fingerprint/detect
Category: com.canonical.plainbox::fingerprint
... 8< -------------------------------------------------------------------------
Enter sudo password:

found 1 devices
Device at /net/reactivated/Fprint/Device/0
Using device /net/reactivated/Fprint/Device/0
Fingerprints for user binli on Synaptics Sensors (press):
 - #0: right-index-finger

**Review by pieqq — APPROVED** [review]
From the look of it and the outcome provided, it looks all good. Sorry for the long delay in approving this!

**Pull request merged**
