### PR TITLE
Bash completion support for checkbox-cli tool

### PR DESCRIPTION
**Pull request by pseudocc**
## Description

Describe your changes here:

- Automatically generate bash completion with python3-argcomplete.
- Use `ArgumentParser.add_subparsers` to replace the former sub command parsing logics.
- Make `plainbox.impl.clitools.CommandBase.register_arguments` a static function, so we don't need to instantiate while adding parameters for each sub parser.
- Use an action(`WarnDeprecated`) to print warning messages for deprecated sub commands.
- Add corresponding completers for each parameters(both top parser and sub parsers).

## Resolved issues

None.

## Documentation

No functionality changes.

- [x] Automated tests are included for the changed functionality in this PR. If to be merged without tests, please elaborate why.
- [x] Necessary documentation is provided for the changed functionality in this PR (tests are documentation, too).

## Tests

- [x] Steps to follow for reviewer to run & manually test are provided.
    - Build and install the packages.
    - Test the bash completion thing manually:
        - Type `checkbox-cli run <tab><tab>`
        - Type `checkbox-cli run com.canonical.certification::after-suspend-<tab><tab>`
        - Type `checkbox-cli list <tab><tab>`
        - Etc..
    - Run some commands:
        - Type `checkbox-cli run com.canonical.certification::dpkg`
        - Type `checkbox-cli list`
        - Etc..
- [x] A list of what tests were run and on what platform/configuration is provided.
    - Since there is no functionality changes, so I did not test it that thoroughly.

### CODE REVIEW

**Review by yphus — CHANGES_REQUESTED** [review]
Since there's now a dependency on `python3-argcomplete`, please add it to the checkbox-ng/debian/control file. Don't worry about xenial, we stopped building debs for it. But for checkbox core snap we keep maintaining checkbox16 so I'd add the [pypi name of the package](https://pypi.org/project/argcomplete/) here: https://github.com/canonical/checkbox/blob/main/checkbox-core-snap/snap/snapcraft.yaml#L203

**Comment by pseudocc** [comment]
> Since there's now a dependency on `python3-argcomplete`, please add it to the checkbox-ng/debian/control file. Don't worry about xenial, we stopped building debs for it. But for checkbox core snap we keep maintaining checkbox16 so I'd add the [pypi name of the package](https://pypi.org/project/argcomplete/) here: https://github.com/canonical/checkbox/blob/main/checkbox-core-snap/snap/snapcraft.yaml#L203

Hi Sylvain, I already added this dependency to the [checkbox-ng/debian/control](https://github.com/canonical/checkbox/pull/26/files#diff-622826d8694029fed987aa1bf25a975c42813131b8ca948cd8ce8448b8feb988), did I miss any of the fields, or you might happen to miss noticing this?

**Review by yphus — CHANGES_REQUESTED** [review]
My bad, I left a comment about `debian/control` based on the discussion you had with Pierre on MM. Just add the python dependency to the checkbox-core-snap please.

One last thing, don't bump the version number in `checkboxng/debian/changelog`, only the release tools are supposed to do it. Let's just run `dch -a`.

**Comment by pseudocc** [comment]
> My bad, I left a comment about `debian/control` based on the discussion you had with Pierre on MM. Just add the python dependency to the checkbox-core-snap please.
> 
> One last thing, don't bump the version number in `checkboxng/debian/changelog`, only the release tools are supposed to do it. Let's just run `dch -a`.

No problem, I reverted my changes to `checkbox-ng/debian/changelog` and ran `dch -a` instead.
But for the checkbox-core-snap, I don't know if [this](https://github.com/canonical/checkbox/pull/26/files#diff-be78cb85afaae978c4514d79e5c2739f177e375377a8747e3bdab4ded34e9e2a) will gonna work, I have very limited knowledge of snapcraft.

**Comment by pseudocc** [comment]
I made a fork sync by mistake, reopen this PR.

**Comment by pieqq** [comment]
Hi!

I finally found some time to test this.

I tried building the checkbox and checkbox22 snaps like so:

```
cd checkbox-core-snap
./prepare.sh series22
cd series22
snapcraft

# Ended up with checkbox22_1.30.dev_amd64.snap

cd ../../checkbox-snap
./prepare_classic.sh series_classic22
cd series_classic22
snapcraft

# Got checkbox_2.3.dev_amd64.snap
```

I then installed them on a test device:

```
sudo snap install checkbox22_1.30.dev_amd64.snap --dangerous
sudo snap install checkbox_2.3.dev_amd64.snap -dangerous --classic
```

But the autocompletion does not work.

If, from bash, I run:

```
checkbox.checkbox-cli list <tab><tab>
```
I get a list of the files in the current directory, and that's all.

Same for `checkbox.checkbox-cli run <tab><tab>`, etc.

I also tried going into the snap using `checkbox.shell`, then run the `checkbox-cli` commands directly from there, but got similar results.

I'm not sure if the invokation of the commands is different when we run checkbox-cli from the snap. For information:

```
# Enter the snap
$ checkbox.shell
checkbox runtime shell, type 'exit' to quit the session
$ which checkbox-cli
/snap/checkbox22/current/bin/checkbox-cli
$ cat /snap/checkbox22/current/bin/checkbox-cli
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys
from checkbox_ng.launcher.checkbox_cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

In the `setup.py` from checkbox-ng, `checkbox-cli` is declared as an entry point like so:

```
   entry_points={
        'console_scripts': [
            'checkbox-cli=checkbox_ng.launcher.checkbox_cli:main',
   (...)
```

**Comment by pseudocc** [comment]
Hi pieqq,

Thank you for you efforts, I did not test whether this would work for snaps, I just tested the debian packages and it works like a charm. 

I am not quite familiar with snap packaging process, but I suppose that there should be rules to place the completion script to the correct place like these 2 files do: 
[checkbox-ng/debian/checkbox-ng.bash-completion](https://github.com/canonical/checkbox/pull/26/files#diff-edd8165fab6dccc5d3899d98ec9a4f79570954450bccd208eb6efa806b3556f8), [checkbox-ng/debian/completions/checkbox-cli](https://github.com/canonical/checkbox/pull/26/files#diff-21b570ecc58b6aa2ba795d67f920f13fc006577d80a5df616a5174e4b21db993).

If you may provide me some hints on it, that would be of great help.
Unfortunately, ncov2019 just got me these days and my employee probation review is coming and I still have a couple of items to do, I might investigate this later on.

My MM: pseudoc.

Sincerely,
pseudocc.

**Comment by pieqq** [comment]
I know Checkbox uses some kind of wrapper to provide the `checkbox-cli` command in the snap. However, I'm not entirely sure how that works, and how that could interact with `argcomplete`. Maybe @kissiel or @jocave would have an idea?

**Comment by yphus** [comment]
Please rebase your work on top of current main branch

**Comment by yphus** [comment]
Closing this for now. If auto-completion can work with snaps and debs please reopen.

**Pull request closed without merging**
