### PR TITLE
Ask tester about available graphics ports and adapters instead of relying on resource job

### LINKED ISSUE #56: LP1982288: Displayport job be skipped since gnome-randr cannot get DP information
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1982288

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2022-07-20 03:13:19	| 6	| Critical	| False  	|

## Description
[Summary]
There are two output port, HDMI and Displayport, on "All In One" DUT.
But "gnome-randr" cannot get the information of Displayport, cause the checkbox cases related to Displayport are skipped automatically.
  - See: https://certification.canonical.com/hardware/202207-30419/submission/272693/test/168578/result/27221500/

If Windowing System is Wayland, checkbox grabs the info of monitor via  "gnome-randr" command.
   commit: https://git.launchpad.net/plainbox-provider-resource/commit/?id=8901ac96bb0b52d54c9501240b07b6a95783ced9

[Steps to reproduce]
1. Boot into OS
2. Run 'gnome-randr' command to get the information of physical monitors

[Expected result]
It should give HDMI and DP information

[Actual result]
Only HDMI information

gnome-randr's output on DAKAR-DGPU-EVT-C6

```
supports-mirroring: true
layout-mode: physical
supports-changing-layout-mode: false
global-scale-required: false
renderer: "native"
legacy-ui-scaling-factor: 1

logical monitor 0:
x: 0, y: 0, scale: 1, rotation: normal, primary: yes
associated physical monitors:
 HDMI-1 DEL OptiPlex AIO 0x44474c78

HDMI-1 DEL OptiPlex AIO 0x44474c78
  1920x1080@62.040439605712891	1920x1080 	62.04*+   	[x1.00+, x2.00]
                  1920x1080@60	1920x1080 	60.00     	[x1.00+, x2.00]
  1680x1050@59.883251190185547	1680x1050 	59.88     	[x1.00+, x2.00]
   1440x900@59.901458740234375	1440x900  	59.90     	[x1.00+]
  1280x1024@60.019741058349609	1280x1024 	60.02     	[x1.00+]
                   1280x720@60	1280x720  	60.00     	[x1.00+]
   1024x768@60.003841400146484	1024x768  	60.00     	[x1.00+]
    800x600@60.316539764404297	800x600   	60.32     	[x1.00+]
is-builtin: false
display-name: "Dell Inc. 23\""
```

[Failure rate]
always

[Additional Info]
CID: 202207-30419, 202207-30420
SKU: DAKAR-DGPU-EVT-C6, DAKAR-UMA-EVT-C4
Image: dell-bto-jammy-jellyfish-chansey-X21-20220704-2.iso

## Attachments
[HDMI and Displayport output port](https://api.launchpad.net/devel/bugs/1982288/+attachment/5604199/data)
[DAKAR-UMA-EVT-C2_only_DP_output](https://api.launchpad.net/devel/bugs/1982288/+attachment/5604201/data)
[output.tar.xz](https://api.launchpad.net/devel/bugs/1982288/+attachment/5611831/data)

Tags:
['jammy-test']

### PR DESCRIPTION
**Pull request by pieqq**
## Description

The display resource job has always been unreliable to assess what graphics ports were available on a device, because the information provided by the graphics drivers and/or xrandr. Things have not gone better with 22.04, which switched to Wayland, forcing us to use gnome-randr, which introduced additional issues.

In addition, more and more devices must be tested using a USB-C to HDMI/DP video adapter. This is a different use case than the one handled by the existing `has_usb_type_c`.

After discussing with QA team, the proposed solution is two-fold:

1. introduce manifest entries for graphics ports. When running Checkbox, if tester selected any jobs that requires to test specific graphics ports (HDMI, DP, VGA, DVI), they will be presented with the following Manifest screen, with a new section ("Does this machine have the following graphics ports?")
2. split `has_usb_type_c` manifest entry into
    a. `has_usbc_data` for jobs testing data transfer (USB drives, Ethernet, keyboard, etc.)
    b. `has_usbc_video` for jobs testing video through USB-C connector

image

The docking jobs have also been updated to take these manifest entries into account.

Finally, the display resource job was removed. Some jobs that were using display resource but were not given a manifest entry (RCA and S-Video) have been kept with the requirement to `display` resource job removed. These jobs are not used in any test plans we actually use regularly, and the display requirement probably didn't work in the first place...

## Resolved issues

Fix #56 

## Tests

After setting up the testing environment as described in the [contributing guide](https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md), unit tests pass for `base` and `resource` providers:

```
checkbox/providers/base $ ./manage.py test
(...)
Ran 1079 tests in 41.949s

OK

checkbox/providers/resource $ ./manage.py test
(...)
Ran 64 tests in 4.699s

OK
```

The validation tests (`./manage.py validate`) also pass for both Base and Resource providers.

I also ran the following tests:

### Test 1

1. Run `checkbox-cli` and select 20.04 manual test plan
4. Select Monitor and Audio jobs
5. Make sure the proper manifest entries are available.
6. Select `Yes` for DisplayPort, and `No` for HDMI, VGA, DVI
7. Check that the DisplayPort are run and the HDMI/VGA/DVI jobs are skipped

### Test 2

1. Run `checkbox-cli` and select Dock Cert test plan
2. Select jobs that require graphics ports and/or adapters
3. Make sure the proper manifest entries are available.
4. Select `Yes` for DisplayPort, and `No` for HDMI, VGA, DVI
5. Check that the DisplayPort are run and the HDMI/VGA/DVI jobs are skipped

### Test 3

1. Run `checkbox-cli` and select 22.04 manual test plan
4. Select Monitor and Audio jobs
5. Make sure the proper manifest entries are available.
6. Select `Yes` for DisplayPort, and `No` for HDMI, VGA, DVI
7. Select `Yes` for "USB Type-C Video Adapter (USB-C to HDMI/DP/...)"
8. Check that the DisplayPort are run and the HDMI/VGA/DVI jobs are skipped
9. Check that USB-C to DisplayPort/HDMI/VGA are run

### Test 4

1. Run `checkbox-cli` and select 22.04 full test plan
2. Select USB jobs that previously required `has_usb_type_c`, such as `usb-c/c-to-a-adapter/hid`, `usb-c/hid`, `usb-c/insert`...
3. Make sure the proper manifest entries are available.
4. Select `Yes` to "USB Type-C Data (e.g. HID, Drives, Ethernet)"
5. Check that the selected jobs are executed like before

### Test 5

1. Run `checkbox-cli` and select 22.04 full test plan
2. Select USB jobs that previously required `has_usb_type_c`, such as `usb-c/c-to-a-adapter/hid`, `usb-c/hid`, `usb-c/insert`...
3. Make sure the proper manifest entries are available.
4. Select `No` to "USB Type-C Data (e.g. HID, Drives, Ethernet)"
5. Check that the selected jobs are skipped

### CODE REVIEW

**Comment by pieqq** [comment]
@p-gentili I added you as a reviewer because of the change in the automated job. If this lands, this might require an update because the new `manifest.has_hdmi` requirement that replaces `display.hdmi` is manual, i.e. a tester must select if there is such a port or not on the device before starting the test. However, this can be automated if a `manifest.json` is provided before running the tests.

**Comment by p-gentili** [comment]
@pieqq thanks. I will review it after the holiday but I just want to make sure xrandr and gnome-randr will still be installed after we merge this PR since they're used in the hdmi hotplug job.

**Comment by pieqq** [comment]
Don't worry: both xrandr and gnome-randr will still be packaged because
they are still required for some rotation and resolution tests.

**Review by yphus — APPROVED** [review]
Amazing work. thanks a lot Pierre. Manifest entries for this type of jobs should have been deployed a while ago as indeed detection via xrandr or other sw methods is not reliable.

**Pull request merged**
