### PR TITLE
[checkbox-ce-oem] Add timedatectl test in strict-confinement mode (New)

### PR DESCRIPTION
**Pull request by rickwu666666**
## Description
Add timedatectl test for testing if timezone and NTP time sync can be configured in strict-confinement mode. This test rely on [test snap](https://code.launchpad.net/~oem-qa/+git/test-strict-confinement/+ref/master).

## Tests
Test result pass:
https://certification.canonical.com/hardware/202304-31486/submission/368054/

Test result failed without connect interface:
https://certification.canonical.com/hardware/202304-31486/submission/368057/

### CODE REVIEW

**Comment by stanley31huang** [comment]
I think we need to have post-suspend for timedate control tests as well.

Another point I would like to raise here is, is the interface connection will be connected automatically? If not, the confinement related tests will be skipped.

**Comment by rickwu666666** [comment]
> Another point I would like to raise here is, is the interface connection will be connected automatically? If not, the confinement related tests will be skipped.
No the interfaces connect won't be automatically. It's rely on manually or via a setup script. And yes, if the interfaces are not connected before the test, than the test will be skipped. And this is the reason which I put the requires of slot and plug.

**Comment by rickwu666666** [comment]
list-bootstrapped of timedatectl:
com.canonical.certification::connections
com.canonical.certification::lsb
com.canonical.certification::snap
com.canonical.contrib::strict-confinement/timedatectl-timezone
com.canonical.certification::rtc
com.canonical.certification::sleep
com.canonical.certification::suspend/suspend_advanced_auto
com.canonical.contrib::after-suspend-strict-confinement/timedatectl-timezone
com.canonical.contrib::strict-confinement/timedatectl-ntp
com.canonical.contrib::after-suspend-strict-confinement/timedatectl-ntp

list-bootstrapped of mediacare:
com.canonical.certification::lsb
com.canonical.plainbox::manifest
com.canonical.certification::snap
com.canonical.contrib::strict-confine/mediacard/sdhc-insert
com.canonical.certification::sleep
com.canonical.certification::rtc
com.canonical.certification::suspend/suspend_advanced_auto
com.canonical.contrib::after-suspend-strict-confine/mediacard/sdhc-insert
com.canonical.contrib::strict-confine/mediacard/sdhc-storage
com.canonical.contrib::after-suspend-strict-confine/mediacard/sdhc-storage
com.canonical.contrib::strict-confine/mediacard/sdhc-remove
com.canonical.contrib::after-suspend-strict-confine/mediacard/sdhc-remove

**Comment by rickwu666666** [comment]
@stanley31huang
I've pushed the update to add post suspend parts. Thanks for the review.

**Comment by stanley31huang** [comment]
LGTM for now, but I would like to separate those jobs and test plans into following structure and also consistent naming rule.
```
root -> units -> test_plans.pxu
                    -> jobs.pxu
```

**Review by stanley31huang — APPROVED** [review]
LGTM, but we need another PR to structure the test plan and job.

**Pull request merged**
