### PR TITLE
Fix modprobe_attachment and sysctl_attachment failed in remote mode (BugFix)

### PR DESCRIPTION
**Pull request by eugene-yujinwu**
[Uploading test-result.zip…]()
When run the information attachment job in remote mode, the sysctl_attachment and modprobe_attachment always failed. If I run it with the root user, the job will be passed without problem.  

## Description
The sysctl_attachment and modprobe_attachment job will failed in remote mode. 

## Resolved issues
The sysctl_attachment and modprobe_attachment job will failed in remote mode. 

## Tests
Attached the test report for which run the test before the fix in local/remote mode, after the fix in local/remote mode.

### CODE REVIEW

**Review by Hook25 — APPROVED** [review]
Makes sense, before merging this can you copy-paste here the error message so that we can see that this is a permission error? (the link in your report is broken for some reason)

**Comment by eugene-yujinwu** [comment]
[Uploading test-result.zip…]()

**Comment by eugene-yujinwu** [comment]
the error info before the fix:
--------------------------------------------------------------------------------
Outcome: job passed
----------------------------[ Running job 28 / 29 ]-----------------------------
-------------------[ Attach the contents of /etc/modprobe.* ]-------------------
ID: com.canonical.certification::modprobe_attachment
Category: Informational tests
--------------------------------------------------------------------------------
find: Failed to change directory: /tmp/cwd-qjd02l9n.8e97016a9495dccd7a89c0ff341c8acc36fe835ff7dc3d91f3fee9d957c60f89: Permission denied
find: Failed to restore initial working directory: /tmp/cwd-qjd02l9n.8e97016a9495dccd7a89c0ff341c8acc36fe835ff7dc3d91f3fee9d957c60f89: Permission denied
--------------------------------------------------------------------------------
Outcome: job failed
----------------------------[ Running job 29 / 29 ]-----------------------------
---------------------[ Attach sysctl configuration files. ]---------------------
ID: com.canonical.certification::sysctl_attachment
Category: Informational tests
--------------------------------------------------------------------------------
find: Failed to change directory: /tmp/cwd-rlvpsmgc.ffa0da6b1c683aed49f2375cb7c30c8e9519afacb0783a0fe124c411f32d134f: Permission denied
find: Failed to restore initial working directory: /tmp/cwd-rlvpsmgc.ffa0da6b1c683aed49f2375cb7c30c8e9519afacb0783a0fe124c411f32d134f: Permission denied
--------------------------------------------------------------------------------
Outcome: job failed
-----------------------------[ Running job 1 / 2 ]------------------------------
-------------------[ Attach the contents of /etc/modprobe.* ]-------------------
ID: com.canonical.certification::modprobe_attachment
Category: Informational tests
--------------------------------------------------------------------------------
find: Failed to change directory: /tmp/cwd-jgwfb48m.8e97016a9495dccd7a89c0ff341c8acc36fe835ff7dc3d91f3fee9d957c60f89: Permission denied
find: Failed to restore initial working directory: /tmp/cwd-jgwfb48m.8e97016a9495dccd7a89c0ff341c8acc36fe835ff7dc3d91f3fee9d957c60f89: Permission denied
--------------------------------------------------------------------------------
Outcome: job failed
-----------------------------[ Running job 2 / 2 ]------------------------------
---------------------[ Attach sysctl configuration files. ]---------------------
ID: com.canonical.certification::sysctl_attachment
Category: Informational tests
--------------------------------------------------------------------------------
find: Failed to change directory: /tmp/cwd-qztz939_.ffa0da6b1c683aed49f2375cb7c30c8e9519afacb0783a0fe124c411f32d134f: Permission denied
find: Failed to restore initial working directory: /tmp/cwd-qztz939_.ffa0da6b1c683aed49f2375cb7c30c8e9519afacb0783a0fe124c411f32d134f: Permission denied
--------------------------------------------------------------------------------
Outcome: job failed

**Comment by Hook25** [comment]
We are having some problems with the uploads today, here are the outputs, the fix works:
- [before_fix.pdf](https://github.com/canonical/checkbox/files/15147716/before_fix.pdf)
- [after_fix.pdf](https://github.com/canonical/checkbox/files/15147720/after_fix.pdf)

(these are submissions.html -> pdf because GH doesn't like html files)

**Comment by eugene-yujinwu** [comment]
@Hook25 thank you for your quick merge!

**Pull request merged**
