### PR TITLE
pc-sanity: check-production-suite should be run for any later versions (BugFix)

### PR DESCRIPTION
**Pull request by medicalwei**
## Description

Run check-production-suite also for 24.04 and later versions

### CODE REVIEW

**Review by xanthein — COMMENTED** [review]
I think in 24.04, stella and sutton will create platform archives as somerville. Should we also check this?

**Comment by KaiChuan-Hsieh** [comment]
Yes, we should also check it for Stella and Sutton.

**Review by xanthein — APPROVED** [review]
LGTM

**Comment by Artur-at-work** [comment]
Merged in https://github.com/canonical/checkbox/pull/1624, closing this as duplicate.

**Pull request closed without merging**
